### ISSUE TITLE
Possible incorrect tear down behavior

### ISSUE THREAD

**Issue by digitalsadhu** [JonathanPrince/loopback-component-fixtures#10]
Thinking about it, I think the following line could probably be considered a bug. 
https://github.com/JonathanPrince/loopback-component-fixtures/blob/master/index.js#L74

I'm not sure it's appropriate to wipe everything regardless of whether a fixture exists for a model/table
It would probably be a good idea to automigrate only the tables where there are fixtures.

**Comment by JonathanPrince** [comment]
good point, it does blow away everything... could be a problem if the db contains seed data but can also be useful for removing non-fixtured model data created by tests. The teardown should probably only remove fixtured data, and this behaviour could be used as to destroy all data.

**Comment by digitalsadhu** [comment]
Might have to have a look at this when I get a chance as would make life easier when trying to do things like cache auth tokens across requests to speed up tests.
