### ISSUE TITLE
3.0.0 support

### ISSUE THREAD

**Issue by dmtrs** [JonathanPrince/loopback-component-fixtures#16]
Is there any plans to add support for loopback version `3.0.0`. When trying to use this component with loopback 3.0.0 I get the following error:

``` js
Error: app.model(modelName, settings) is no longer supported. Use app.registry.createModel(modelName, definition) and app.model(ModelCtor, config) instead.
```

Which refers in index.js line 83

**Comment by JonathanPrince** [comment]
Hi @dmtrs, thanks for letting me know, will look into this in the next few days
