### ISSUE TITLE
Please submit latest to npm

### ISSUE THREAD

**Issue by rhodul** [JonathanPrince/loopback-component-fixtures#26]
npm install --save-dev loopback-component-fixtures
will
put "loopback-component-fixtures": "^1.0.2", in my package.json

the installed package.json says "version": "1.0.2" and yet index.js has:
  var Fixtures = app.model('fixtures', {
    dataSource: false,
    base: 'Model'
  });

**Comment by JonathanPrince** [comment]
Hi @rhodul I've published the current master to npm as 1.1.0
